### ISSUE TITLE
[Bug]: java.lang.NoSuchMethodError: 'javax.servlet.http.HttpServletMapping 

### ISSUE THREAD

**Issue by kenu** [eGovFramework/egovframe-boot-sample-java-config#7]
### 연락처 Contact

kenu.heo@gmail.com

### 오류 내용 Error Description

오류를 발견했어요. I found an error.
java.lang.NoSuchMethodError: 'javax.servlet.http.HttpServletMapping javax.servlet.http.HttpServletRequest.getHttpServletMapping()'

<img width="1440" alt="스크린샷 2023-06-14 오후 8 01 35" src="https://github.com/eGovFramework/egovframe-boot-sample-java-config/assets/718691/a1a75ca7-c6a7-4381-ac7b-43067a3acf88">

<img width="1440" alt="스크린샷 2023-06-14 오후 8 01 35" src="https://github.com/eGovFramework/egovframe-boot-sample-java-config/assets/718691/ec3f7025-3d5a-488a-9128-5b11cfb7c5b8">

### 오류 재현 방법 How to reproduce the error

(다음은 예시이며, 내용을 덮어 써 주세요. The following is an example, please overwrite the content.)

 1. 빌드
 2. mvn spring-boot:run
 3. http://localhost:8080 접속시 500에러

<img width="1440" alt="스크린샷 2023-06-14 오후 8 07 04" src="https://github.com/eGovFramework/egovframe-boot-sample-java-config/assets/718691/a93382ce-d3d6-46fc-be2c-078c8f60c995">

### 환경정보 Environmental Information

 - OS정보 Operating System: macOS Ventura 13.4(22F66)
 - 표준프레임워크 버전 eGovFrame Version: 4.1
 - JDK(JRE) 정보: openjdk version "11.0.18" 2023-01-17 LTS
 - WAS 정보: default
 - DB 정보: default
 - 기타 환경 정보 Other environmental information: -

### 어느 브라우저를 사용했나요? Which browser did you use?

Chrome

### 에러 로그 Error Logs

```shell
Root Cause

java.lang.NoSuchMethodError: 'javax.servlet.http.HttpServletMapping javax.servlet.http.HttpServletRequest.getHttpServletMapping()'
	org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:171)
	org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316)
	org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1401)
	org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1145)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1084)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
Note The full stack trace of the root cause is available in the server logs.
```
```

**Comment by miniplugin** [comment]
위 이슈에 관련된 소스를 수정하였습니다.(아래)
https://github.com/eGovFramework/egovframe-boot-sample-java-config/pull/10

**Comment by delvering17** [comment]
javaee-api 7.0과 tomcat 9.0.73의 서블릿 버전이 맞지 않아 생긴 버그 같습니다.
저는 다음과 같이 pom.xml에서 javaee-api 버전 수정하여 조치했습니다. 

```
<dependency>
    <groupId>jakarta.platform</groupId>
    <artifactId>jakarta.jakartaee-api</artifactId>
    <version>9.1.0</version>
    <scope>provided</scope>
</dependency>
```

**Comment by miniplugin** [comment]
[위 delvering17님의 처리가 더 간단하여서 소스에 적용해서 커밋해 놓았습니다. 코멘트 주셔서 감사합니다.^^](https://github.com/eGovFramework/egovframe-boot-sample-java-config/pull/10/commits/eba013b03a0ec20b532f71690cb9006c3ff651cf)

**Comment by eGovFrameSupport** [comment]
표준프레임워크에 대한 지속적인 참여에
대단히 감사드립니다.

**Comment by eGovFrameSupport** [comment]
[2023 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'23년 4월 10일부터 8월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2023 전자정부 표준프레임워크 컨트리뷰션"을 실시 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.

https://forms.gle/g5cKfG5rnNrqvqjaA

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 감사장과 표준프레임워크 오픈커뮤니티에서 소정의 기념품을 택배 배송 해 드립니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.
