### ISSUE TITLE
[의견]: Gradle 적용 가능 샘플이나 가이드 문서(md) 요청

### ISSUE THREAD

**Issue by yangdk73** [eGovFramework/egovframe-boot-sample-java-config#8]
### 연락처 Contact

yangdk73@gmail.com

### 추가 요청 기능명 Feature Name

gradle 적용 샘플이나 가이드 내용 추가 요청

### 기능 상세 설명 Feature Description

최근 빌드관리도구를 Maven 보다는 Gradle을 많이 사용하고 있습니다.
샘플에는 Maven 설정에 대한 내용만 있고, Gradle 설정에 대한 내용이 없네요.
샘플 프로젝트를 추가해주시거나 readme.md에 라도 gradle설정가이드와 maven에서 gradle 전환하는 관련 설정  내용이 추가 되면 개발자에게 많은 도움이 될 것 같습니다.

### 솔루션 상세 Solution Details

maven에서 gradle 전환 관련 내용은 아래 url 참고해주세요.
더 좋은 내용이 있다면 그걸로 추가해주시면 더 좋을 것 같습니다.

### 솔루션 관련 URL Solution-related URLs

https://www.lesstif.com/spring/maven-gradle-129007766.html

**Comment by eGovFrameSupport** [comment]
안녕하세요.
표준프레임워크센터 입니다.

해당 의견은 내부적으로 검토 후 차후 가이드 문서 작성시 반영할 수 있도록 하겠습니다.
표준프레임워크 발전을 위해 소중한 의견 감사합니다.

**Comment by eGovFrameSupport** [comment]
[2023 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'23년 4월 10일부터 8월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2023 전자정부 표준프레임워크 컨트리뷰션"을 실시 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.

https://forms.gle/g5cKfG5rnNrqvqjaA

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 감사장과 표준프레임워크 오픈커뮤니티에서 소정의 기념품을 택배 배송 해 드립니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.
